name: Deploy on push

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push todomvc image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/todomvc ./todomvc
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/todomvc

      - name: Build and push html image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/html ./html
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/html

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/todomvc
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/html
            docker stop todomvc || true
            docker stop html || true
            docker rm todomvc || true
            docker rm html || true
            docker run -d --name todomvc -p 8081:8081 ${{ secrets.DOCKER_HUB_USERNAME }}/todomvc
            docker run -d --name html -p 8080:80 ${{ secrets.DOCKER_HUB_USERNAME }}/html
